version: "3.9"
 services:
    mysqldatabase:
       image: jparas/mysql
       container_name: mysqldatabase
       ports:
          - 3306:3306
       volumes:
          - /c/Users/jayash.yadav/Desktop/data:/var/lib/mysql 
    frontend:
       image: jparas/app
       container_name: health
       command: sh -c "python manage.py wait_for_db  && python manage.py runserver 0.0.0.0:8000"
       ports:
          - 8000:8000
       depends_on:
          - mysqldatabase